# PostgreSQL Configuration
# Ensure the pg gem is defined in your Gemfile:
# gem "pg"

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres # PostgreSQL kullanıcı adınız
  password: # PostgreSQL şifreniz (varsa)
  host: localhost # PostgreSQL sunucu adresi (genellikle localhost)

development:
  <<: *default
  database: myapp_development # Geliştirme ortamı için veritabanı adı

test:
  <<: *default
  database: myapp_test # Test ortamı için veritabanı adı

# Production configuration should be more secure.
# Make sure to set your environment variables in production.
production:
  <<: *default
  database: myapp_production # Üretim ortamı için veritabanı adı
  username: myapp # Üretim ortamı için PostgreSQL kullanıcı adı
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %> # Şifreyi environment variable olarak tanımlayın
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %> # Üretim sunucusunun adresi
